[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  [[plugins]]
package = "netlify-plugin-ghost-markdown"

   [plugins.inputs]
   ghostURL = "https://hellowojo.ghost.io"
   ghostKey = "76a0fef61828decf1420b2a49d"
   # Optional: Directory containing posts (_posts/ directory by default)
  postsDir = "./content/posts/"
